services:

###> containers ###
    ###> maildev ###
    
    ### base config ###
    maildev-base:
        image: ${MAILER_IMAGE}
        container_name: ${APP_NAME}_maildev

    ## local config ###
    maildev-local:
        extends: maildev-base
        command: 'bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS'
        ports:
            - '${MAILER_PORT:-25}:25'
            - '${MAILER_UI_PORT:-1080}:80'
    ### maildev ###
### containers ###